;;; pomodoro-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (file-name-directory load-file-name)) (car load-path)))



;;; Generated autoloads from pomodoro.el

(autoload 'pomodoro-start "pomodoro" "\


(fn ARG)" t)
(register-definition-prefixes "pomodoro" '("play-pomodoro-" "pomodoro-"))

;;; End of scraped data

(provide 'pomodoro-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; pomodoro-autoloads.el ends here
